# Generated by Django 5.1 on 2024-08-23 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_alter_farmer_options_farmer_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
